require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

# def ios_pods
  pod 'FBSDKCoreKit' # <- Add this line HERE
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn', '~> 5.0.2'
# end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)

      if text != replace
          puts "Fix: " + name
          system("chmod +w " + name)
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end

target 'parkauthority_37803' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
  )
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

  target 'parkauthority_37803Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3' , 'Flipper' => '0.88.0' })
  

  post_install do |installer|
    flipper_post_install(installer)
    # react_native_post_install(installer,
    # :mac_catalyst_enabled => false)
    find_and_replace("Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h",
    "  atomic_notify_one(state);", "  folly::atomic_notify_one(state);")
    installer.pods_project.targets.each do |target| 
      target.build_configurations.each do |config| 
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0' 
      end
    end
    installer.pods_project.build_configurations.each do |config| 
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64" 
    end
  end
end